import os
import pandas as pd
import matplotlib.pyplot as plt
from mplchart.chart import Chart
from mplchart.primitives import Candlesticks, Volume
from mplchart.indicators import SMA, RSI, MACD
from matplotlib.backends.backend_pdf import PdfPages
from ib_insync import IB, Stock, util
from pandas.tseries.offsets import BDay

# File paths
tickers_file = "tickers.txt"
predictions_file = "/Users/alecjeffery/Documents/Playgrounds/Python/spacetimeformer_stocks/oos_predictions_current.csv"
# predictions_file = "/path/to/oos_predictions_current.csv"
output_pdf = "all_charts.pdf"

# Initialize IB connection
ib = IB()
ib.connect('127.0.0.1', 7496, clientId=11)

# Function to fetch adjusted close price and implied volatility data
def get_historical_data(ticker):
    contract = Stock(ticker, 'SMART', 'USD')
    ib.qualifyContracts(contract)

    historical_data = ib.reqHistoricalData(
        contract,
        endDateTime='',
        barSizeSetting='1 day',
        durationStr='2 Y',
        whatToShow='ADJUSTED_LAST',
        useRTH=True
    )
    data = util.df(historical_data)
    data.set_index('date', inplace=True)

    try:
        iv_data = ib.reqHistoricalData(
            contract,
            endDateTime='',
            barSizeSetting='1 day',
            durationStr='2 Y',
            whatToShow='OPTION_IMPLIED_VOLATILITY',
            useRTH=True
        )
        iv_df = util.df(iv_data)
        iv_df.set_index('date', inplace=True)
        iv_df = iv_df.rename(columns={'close': 'vclose'})
        data = data.join(iv_df[['vclose']], how='left')
    except Exception:
        print(f"Warning: No implied volatility data found for {ticker}. Setting vclose to NaN.")
        data['vclose'] = float('nan')

    return data

# Function to calculate percentage change
def calculate_percentage_change(current, forecast):
    return ((forecast / current) - 1) * 100 if current != 0 else 0

# Function to plot historical price and volatility with predictions
def plot_historical_with_predictions(ticker, position_category, actual_data, prediction_data):
    # Extract predicted data
    predicted_close_values = prediction_data[['Close_1', 'Close_2', 'Close_3', 'Close_4', 'Close_5',
                                              'Close_6', 'Close_7', 'Close_8', 'Close_9', 'Close_10']].values.flatten()
    predicted_volatility_values = prediction_data[['Volatility_1', 'Volatility_2', 'Volatility_3', 'Volatility_4',
                                                   'Volatility_5', 'Volatility_6', 'Volatility_7', 'Volatility_8',
                                                   'Volatility_9', 'Volatility_10']].values.flatten()
    prediction_dates = pd.date_range(start=actual_data.index[-1], periods=11, freq=BDay())[1:]

    final_close_10 = prediction_data['Close_10'].values[0]
    final_volatility_10 = prediction_data['Volatility_10'].values[0]
    last_actual_close = actual_data['close'].iloc[-1]
    last_actual_volatility = actual_data['vclose'].iloc[-1] if 'vclose' in actual_data.columns else float('nan')

    close_pct_change = calculate_percentage_change(last_actual_close, final_close_10)
    volatility_pct_change = calculate_percentage_change(last_actual_volatility, final_volatility_10)

    # Create the plot
    fig, axs = plt.subplots(2, 1, figsize=(10, 6))
    fontdict = {'fontsize': 12}

    axs[0].plot(actual_data.index[-252:], actual_data['close'][-252:], label='Historical Prices', color='blue')
    axs[0].plot(prediction_dates[-252:], predicted_close_values[-252:], label='Predicted Prices', color='red', linestyle='--')
    axs[0].set_title(
        f"{ticker} Close Prices & Forecast: ${final_close_10:.2f} [{close_pct_change:.2f}%]\nPosition: {position_category.upper()}",
        fontdict=fontdict
    )
    axs[0].legend()
    axs[0].grid()

    if 'vclose' in actual_data.columns:
        axs[1].plot(actual_data.index[-252:], actual_data['vclose'][-252:], label='Historical Volatility', color='blue')
    axs[1].plot(prediction_dates[-252:], predicted_volatility_values[-252:], label='Predicted Volatility', color='red', linestyle='--')
    axs[1].set_title(
        f"{ticker} Volatility & Forecast: {final_volatility_10:.2f}% [{volatility_pct_change:.2f}%]",
        fontdict=fontdict
    )
    axs[1].legend()
    axs[1].grid()

    plt.tight_layout()
    return fig

# Function to generate a chart using mplchart
def generate_mplchart(ticker, data):
    indicators = [
        Candlesticks(),
        Volume(),
        SMA(50),
        SMA(200),
        # RSI(9),
        RSI(14),
        MACD(12,26,9),
        MACD(5, 13, 8)
    ]
    chart = Chart(title=ticker, max_bars=250)
    chart.plot(data, indicators)
    fig = plt.gcf()  # Get the current figure generated by mplchart
    return fig

# Main function to process tickers and save charts into a single PDF
def process_tickers_to_pdf():
    pdf_pages = PdfPages(output_pdf)

    with open(tickers_file, 'r') as file:
        tickers = [line.strip().split(',') for line in file]

    predictions_df = pd.read_csv(predictions_file)

    for ticker_info in tickers:
        ticker = ticker_info[0].strip().upper()
        position_category = ticker_info[1].strip().lower()

        try:
            print(f"Fetching data for {ticker}...")
            actual_data = get_historical_data(ticker)
            prediction_data = predictions_df[predictions_df['Unnamed: 0'] == ticker]

            if prediction_data.empty:
                print(f"No prediction data found for {ticker}. Skipping.")
                continue

            print(f"Creating historical chart for {ticker}...")
            hist_fig = plot_historical_with_predictions(ticker, position_category, actual_data, prediction_data)
            pdf_pages.savefig(hist_fig)
            plt.close(hist_fig)

            print(f"Creating mplchart for {ticker}...")
            mpl_fig = generate_mplchart(ticker, actual_data)
            pdf_pages.savefig(mpl_fig)
            plt.close(mpl_fig)

        except Exception as e:
            print(f"Error processing {ticker}: {e}")

    pdf_pages.close()
    print(f"Saved all charts to {output_pdf}")

if __name__ == "__main__":
    process_tickers_to_pdf()