import os
import pandas as pd
from ib_insync import IB, Stock, util
from matplotlib.backends.backend_pdf import PdfPages
from mplchart.chart import Chart
from mplchart.primitives import Candlesticks, Volume
from mplchart.indicators import SMA, RSI, MACD
import matplotlib.pyplot as plt

# File paths
tickers_file = "tickers.txt"
output_pdf = "all_charts.pdf"

# Initialize IB connection
ib = IB()
ib.connect('127.0.0.1', 7496, clientId=11)

# Function to fetch historical data
def get_historical_data(ticker):
    contract = Stock(ticker, 'SMART', 'USD')
    ib.qualifyContracts(contract)

    # Fetch adjusted close price data
    historical_data = ib.reqHistoricalData(
        contract,
        endDateTime='',
        barSizeSetting='1 day',
        durationStr='6 M',
        whatToShow='ADJUSTED_LAST',
        useRTH=True
    )
    data = util.df(historical_data)
    data.set_index('date', inplace=True)
    return data

# Function to generate a chart using mplchart and capture the figure
def generate_chart_as_figure(ticker, data):
    indicators = [
        Candlesticks(),
        Volume(),
        SMA(50),
        SMA(200),
        RSI(9),
        RSI(14),
        MACD(),
    ]
    chart = Chart(title=ticker, max_bars=250)
    chart.plot(data, indicators)
    fig = plt.gcf()  # Get the current figure generated by mplchart
    return fig

# Main function to process tickers and save all charts into a PDF
def process_tickers_to_pdf():
    pdf_pages = PdfPages(output_pdf)

    with open(tickers_file, 'r') as file:
        tickers = [line.strip().split(',')[0] for line in file]

    for ticker in tickers:
        try:
            print(f"Fetching data for {ticker}...")
            data = get_historical_data(ticker)

            print(f"Creating chart for {ticker}...")
            fig = generate_chart_as_figure(ticker, data)

            print(f"Adding chart for {ticker} to PDF...")
            pdf_pages.savefig(fig)
            plt.close(fig)

        except Exception as e:
            print(f"Error processing {ticker}: {e}")

    pdf_pages.close()
    print(f"Saved all charts to {output_pdf}")
    ib.disconnect()

if __name__ == "__main__":
    process_tickers_to_pdf()
